@startuml

title RockstarSays SSD
actor User
participant Slash

group Rockstar Application
User -> Slash: Start
note right: With Splash Screen
User <- Slash: Application Starts

alt Choose/Select Difficulty
User -> Slash: Selcts Difficulty
note right: Easy, Medium, Hard
User <- Slash: Starts Game with Selected Difficulty
User -> Slash: Disable Sound
User <- Slash: Starts Game weith Sound Option
end

loop User Selcts Button Sequence
User <- Slash: Highlights a Button
User -> Slash: Selects Appropriate Button

alt Win
User -> Slash: Reaches Predetermined Score

User <- Slash: Displays Winning Toast
end

alt Lose
User -> Slash: Selects Wrong Button
User <- Slash: Displays Score
end

end

opt Start Over
User <- Slash: Presents Option to Start Over
User -> Slash: User Option
end

end

@enduml